# Generated by Django 4.2.28 on 2026-02-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Доступен'), ('BOOKED', 'Забронирован'), ('BLOCKED', 'Заблокирован')], default='AVAILABLE', max_length=10, verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Слоты расписания',
                'db_table': 'schedule_slots',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('CANCELLED', 'Отменена')], default='CREATED', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='masters.service', verbose_name='Услуга')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='schedule.scheduleslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
