# Generated by Django 4.2.28 on 2026-02-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_slots',
            field=models.ManyToManyField(blank=True, related_name='bookings_all', to='schedule.scheduleslot', verbose_name='Все забронированные слоты'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='schedule.scheduleslot', verbose_name='Начальный слот'),
        ),
    ]
